FROM ubuntu:20.04
LABEL maintainer=falldog

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        g++ \
        make \
    && rm -rf /var/lib/apt/lists/*

VOLUME /code
WORKDIR /code
