FROM alpine:3.9 as alpine-builder
LABEL maintainer=falldog

RUN apk update \
    && apk add --no-cache \
        g++ \
        make \
    && rm -rf /var/cache/apk/*

COPY src/ /code/src/
COPY Makefile.base /code/
WORKDIR /code
RUN make -f Makefile.base


FROM alpine:3.9
RUN apk add --no-cache \
        libstdc++ \
    && rm -rf /var/cache/apk/*

COPY --from=alpine-builder /code/dist/dcinja /app/
WORKDIR /app
ENTRYPOINT [ "/app/dcinja" ]