FROM debian:buster as linux-amd64-builder
LABEL maintainer=falldog

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        g++ \
        make \
    && rm -rf /var/lib/apt/lists/*

COPY src/ /code/src/
COPY Makefile /code/
WORKDIR /code
RUN make


FROM debian:buster
COPY --from=linux-amd64-builder /code/dist/dcinja /app/
WORKDIR /app
ENTRYPOINT [ "/app/dcinja" ]