FROM alpine:3.12 as alpine-builder
LABEL maintainer=falldog

RUN apk update \
    && apk add --no-cache \
        g++ \
        make \
    && rm -rf /var/cache/apk/*

COPY ./ /code/
WORKDIR /code
RUN make


FROM alpine:3.12
RUN apk add --no-cache \
        libstdc++ \
    && rm -rf /var/cache/apk/*

COPY --from=alpine-builder /code/dist/dcinja /app/
WORKDIR /app
ENTRYPOINT [ "/app/dcinja" ]